import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import {UserContextProvider} from '../context/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'title',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
        {children}
        </UserContextProvider>

        </body>
    </html>
  )
}
